//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VehicleRental.Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Category
	{
		public virtual int Id
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual double PriceFixedMileage
		{
			get;
			set;
		}

		public virtual double PriceFullInsurance
		{
			get;
			set;
		}

		public virtual double PriceUnlimitedMileage
		{
			get;
			set;
		}

		public virtual double PricePartialInsurance
		{
			get;
			set;
		}

		public virtual double PriceAdditionalKm
		{
			get;
			set;
		}

		public virtual Category Upper
		{
			get;
			set;
		}

	}
}

