//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VehicleRental.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

    public partial class CreditCard
	{
        [Key]
        public string Digits
		{
			get;
			set;
		}

		public int Month
		{
			get;
			set;
		}

		public int Year
		{
			get;
			set;
		}

		public int Cvc
		{
			get;
			set;
		}

		public string Type
		{
			get;
			set;
		}

	}
}

