//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VehicleRental.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

    public partial class Person
	{
        [Key]
        public string Dni
		{
			get;
			set;
		}

		public string Name
		{
			get;
			set;
		}

		public string Address
		{
			get;
			set;
		}

		public string City
		{
			get;
			set;
		}

		public string PostalCode
		{
			get;
			set;
		}

		public DateTime DateDriverLicense
		{
			get;
			set;
		}

		public virtual ICollection<Reservation> Reservations
		{
			get;
			set;
		}

	}
}

